# Generated by Django 2.1 on 2018-11-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DvD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField(verbose_name='date released')),
                ('last_watched', models.DateField(null=True, verbose_name='last watched')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.DvD')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dvd',
            name='where_stored',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.Location'),
        ),
        migrations.AddField(
            model_name='director',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.DvD'),
        ),
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.DvD'),
        ),
    ]
