# Generated by Django 2.1 on 2019-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='times_watched',
            field=models.IntegerField(default=0, verbose_name='times watched'),
        ),
    ]
