# Generated by Django 2.1 on 2019-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0002_dvd_times_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='is_series',
            field=models.BooleanField(default=False, verbose_name='series'),
        ),
    ]
