# Generated by Django 2.1 on 2018-11-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0002_auto_20181104_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='film',
        ),
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='rotten_tomato_rating',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='film',
        ),
        migrations.AddField(
            model_name='dvd',
            name='actors',
            field=models.ManyToManyField(to='dvds.Actor'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='director',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dvds.Director'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='genres',
            field=models.ManyToManyField(to='dvds.Genre'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
