# Generated by Django 2.1 on 2018-11-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0003_auto_20181104_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='director',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dvds.Director'),
        ),
    ]
