# Generated by Django 2.1 on 2018-11-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0005_auto_20181104_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.Director'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='poster_url',
            field=models.URLField(),
        ),
    ]
