# Generated by Django 2.1 on 2018-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0006_auto_20181104_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='blurb',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
