# Generated by Django 2.1 on 2018-11-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0007_dvd_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
